print("###########################")
print("#                         #")
print("#     Helda Istianty      #")
print("#     2610817120013       #")
print("#                         #")
print("###########################")    